### PR TITLE
Upgrade to latest Jest version 5.3.3

### PR DESCRIPTION
**Pull request by pcvolkmer**
Using gradle the latest dependency version is selected:

```
io.searchbox:jest:5.3.2 -> 5.3.3
\--- com.github.vanroy:spring-data-jest:3.1.0.RELEASE
     \--- com.github.vanroy:spring-boot-starter-data-jest:3.1.0.RELEASE
```
There are some renamed methods within this version which causes errors e.g.
```
java.lang.NoSuchMethodError: io.searchbox.core.Count$Builder.addIndex(Ljava/util/Collection;)Ljava/lang/Object;
```
I have changed related code to match Jest 5.3.3.

### CODE REVIEW

**Comment by VanRoy** [comment]
Hi @pcvolkmer ,

Thanks a lot for your contribution.
Can you explain me what is the major improvement or fix related to this update ? 

Julien.

**Comment by pcvolkmer** [comment]
Hi @VanRoy,

I am a user of *spring-data-jest* and figured out, that Gradle will prefer 5.3.3 over 5.3.2. With the changes made in Jest 5.3.3
* https://github.com/searchbox-io/Jest/commit/a7aa5c58d2a4a3212eae6bb8302c08e2a5b69c6f
* https://github.com/searchbox-io/Jest/commit/a5bfdfe1239d58094bb50dabec98f84a8350fb48
I got the `NoSuchMethodError` at runtime as described in PR description. So I decided to create this patchset for a version of *spring-data-jest* working with Jest 5.3.3.

Paul

**Comment by VanRoy** [comment]
@pcvolkmer Ok great.
Your PR is published on maven central.
Thanks for your help
